import { describe, expect, it } from 'vitest'
import { fromHex, getPublicKey, hash256, schnorrGetPublicKey, scriptP2PK, scripthashFromPubkey, toHex } from '@qbtc/crypto'
import { addressFromPubkey, addressFromScripthash, decodeAddress, validateAddress } from '../../../src/main/brand/crypto'
import { PROFILE } from '../../../src/main/brand/profile'

// eCurrency address goldens. Real-world mainnet vectors from the live mempool
// dump: each row is taken from one tx in
// `GET https://api.ecurrency.org/api/mempool/recent`. These are the most
// authoritative test vectors we have — if our implementation produces the
// same address as the node from the same pubkey, we're byte-compat.

interface PubkeyVector {
  pubkey: string
  scripthash: string
  address: string
}

const MAINNET_PUBKEY_VECTORS: PubkeyVector[] = [
  {
    pubkey: '039b66566d3acb6bd203a0a61f4e0105b84f12e107aaf27f30466807121197d10c',
    scripthash: 'a63aa6b72ec7668ee5529a2d4706b7ac8239a4a2',
    address: 'ECb1CCY6rLbRwcc4e311vpXrZfgDNy9FpGK',
  },
  {
    pubkey: '02b17362c10f06ff75a7039798de7301991fc371aeccf1aba3c8849a2f3f06322c',
    scripthash: '38a3a70af85baab9455c148fa2ce83657d9a484c',
    address: 'ECR1jf3zc22axpFnXRPmuakVieG1P4YRXDm',
  },
]

// scripthash ↔ address pairs (no pubkey known — used only for the
// scripthash→address direction).
const MAINNET_SCRIPTHASH_PAIRS: Array<{ scripthash: string; address: string }> = [
  { scripthash: 'de4bde2de43a35b7538e9992b94f2c29bec01e8b', address: 'ECg7efWkNeao3EGqrMcddjuSnZDowathtn4' },
  { scripthash: 'ad5ef5738c9b3e8de242e75d3f99c5b92a49a25a', address: 'ECbexRaDQ2YYyjWwZpUPrTDguXEdcXtCMGx' },
  { scripthash: 'b9aeee3da2449c03ab85eaa772754459292b1e40', address: 'ECcn4LR59HoeWCznp9UztdRv5raoTesqt4d' },
  { scripthash: 'cd5e217bbc2e368a398ba6130aba5187ea689ca2', address: 'ECea94BV7D3ipwN2XZj8od11BUKY4qRYumY' },
  { scripthash: '827ea2d412a1c9e1f859d9a8daadc4921a0237c4', address: 'ECXkFKJHx5XKLfkArgDpiCo2abGz7oVCA2j' },
  { scripthash: '3795a4207eed2182225da6866b45edfddb095e5c', address: 'ECQvACLDXnTBtYJDWTrtJREzmhgrRQDfMjw' },
]

describe('addressFromPubkey — live mempool vectors', () => {
  it.each(MAINNET_PUBKEY_VECTORS)('derives $address from its pubkey', ({ pubkey, scripthash, address }) => {
    expect(toHex(scripthashFromPubkey(fromHex(pubkey), 'ecdsa'))).toBe(scripthash)
    expect(addressFromPubkey(fromHex(pubkey), 'ecdsa', 'mainnet')).toBe(address)
  })
})

describe('addressFromScripthash / decodeAddress — round-trip with live data', () => {
  it.each(MAINNET_SCRIPTHASH_PAIRS)('encodes and decodes $address', ({ scripthash, address }) => {
    expect(addressFromScripthash(fromHex(scripthash), 'mainnet')).toBe(address)
    const dec = decodeAddress(address)
    expect(dec.network).toBe('mainnet')
    expect(dec.type).toBe('classical')
    expect(toHex(dec.scripthash)).toBe(scripthash)
    expect(validateAddress(address, 'mainnet')).toBe(true)
  })

  it('rejects a mainnet address on the testnet network', () => {
    expect(validateAddress('ECb1CCY6rLbRwcc4e311vpXrZfgDNy9FpGK', 'testnet')).toBe(false)
  })

  it('rejects a tampered checksum', () => {
    // Flip one character in a real address — checksum will fail.
    const real = 'ECb1CCY6rLbRwcc4e311vpXrZfgDNy9FpGK'
    const tampered = real.slice(0, -1) + (real.at(-1) === '1' ? '2' : '1')
    expect(validateAddress(tampered, 'mainnet')).toBe(false)
    expect(() => decodeAddress(tampered)).toThrow()
  })

  it('schnorr keys encode as classical EC… addresses too', () => {
    const sk = fromHex('11'.repeat(32))
    const schnorrAddr = addressFromPubkey(schnorrGetPublicKey(sk), 'schnorr', 'mainnet')
    // The P2PK script pushes a 32-byte key instead of a 33-byte one, so the
    // hash — and the address — differ from the ECDSA one.
    expect(schnorrAddr).not.toBe(addressFromPubkey(getPublicKey(sk), 'ecdsa', 'mainnet'))
    expect(validateAddress(schnorrAddr, 'mainnet')).toBe(true)
    expect(schnorrAddr.startsWith('EC')).toBe(true)
  })
})

// ─── Post-quantum (Falcon-512) addresses ──────────────────────────────
//
// Synthetic deterministic 897-byte pubkey (0x09 version byte + pattern).
// Expected values were generated by this implementation and FROZEN — they
// pin the PQ encoding: scripthash = hash256(P2PK script), 32-byte form.
// The full mnemonic→address chain is pinned in ./falconHd.test.ts.

function syntheticFalconPubkey(): Uint8Array {
  const pk = new Uint8Array(897)
  pk[0] = 0x09
  for (let i = 1; i < pk.length; i++) pk[i] = i % 256
  return pk
}

const PQ_SCRIPTHASH = 'a996d29978cadc7100f8ee23fc408bbcbadc4500564ba02989e55b772494f280'
const PQ_MAINNET_ADDRESS = '26mXaTowE4gsXWzQT2bmBp91du4Ewf2MBqExXmBqTe7FvzXBrtav'
const PQ_TESTNET_ADDRESS = '2A5yGvmNPRopwsCwGmzD7EtNJZMD31jmsjWyBv1wD3yvKr4VcLcq'

describe('post-quantum (falcon512) address encoding', () => {
  it('scripthash = hash256(scriptP2PK(pubkey)), 32 bytes', () => {
    const pk = syntheticFalconPubkey()
    const sh = scripthashFromPubkey(pk, 'falcon512')
    expect(sh.length).toBe(32)
    expect(toHex(sh)).toBe(PQ_SCRIPTHASH)
    expect(toHex(sh)).toBe(toHex(hash256(scriptP2PK(pk))))
  })

  it('encodes the frozen mainnet/testnet PQ addresses', () => {
    const pk = syntheticFalconPubkey()
    expect(addressFromPubkey(pk, 'falcon512', 'mainnet')).toBe(PQ_MAINNET_ADDRESS)
    expect(addressFromPubkey(pk, 'falcon512', 'testnet')).toBe(PQ_TESTNET_ADDRESS)
  })

  it('PQ addresses match the network regex and validate', () => {
    expect(PROFILE.addressRegex.mainnet.test(PQ_MAINNET_ADDRESS)).toBe(true)
    expect(PROFILE.addressRegex.testnet.test(PQ_TESTNET_ADDRESS)).toBe(true)
    expect(validateAddress(PQ_MAINNET_ADDRESS, 'mainnet')).toBe(true)
    expect(validateAddress(PQ_TESTNET_ADDRESS, 'testnet')).toBe(true)
    expect(validateAddress(PQ_MAINNET_ADDRESS, 'testnet')).toBe(false)
  })

  it('decodes round-trip as type pq', () => {
    const dec = decodeAddress(PQ_MAINNET_ADDRESS)
    expect(dec.type).toBe('pq')
    expect(dec.network).toBe('mainnet')
    expect(toHex(dec.scripthash)).toBe(PQ_SCRIPTHASH)
    expect(addressFromScripthash(dec.scripthash, 'mainnet')).toBe(PQ_MAINNET_ADDRESS)
  })

  it('the HD-derived golden address (falconHd v1 cell 0,0,0) is a valid pq address', () => {
    const addr = '26mLXtZ9j3aJx2K2CqM831JT4NQw1nzkYuVcgkTWbdByRMor2N5b'
    expect(validateAddress(addr, 'mainnet')).toBe(true)
    expect(decodeAddress(addr).type).toBe('pq')
  })
})

// ─── Address-shape regexes ────────────────────────────────────────────
//
// The character classes are the EXACT reachable ranges for the magic bytes:
// base58(magic ‖ hash ‖ checksum) over all hashes. The node's testnet range
// once said 2A[678]; it was fixed to 2A[456] after our report (2026-07).

describe('address regexes', () => {
  const tail = '1'.repeat(49)

  it('mainnet matches classical EC… addresses and rejects the testnet shape', () => {
    expect(PROFILE.addressRegex.mainnet.test('ECb1CCY6rLbRwcc4e311vpXrZfgDNy9FpGK')).toBe(true)
    expect(PROFILE.addressRegex.mainnet.test('ECR1jf3zc22axpFnXRPmuakVieG1P4YRXDm')).toBe(true)
    expect(PROFILE.addressRegex.mainnet.test('Et1234567890123456789012345678901234567')).toBe(false)
    expect(PROFILE.addressRegex.mainnet.test('EC')).toBe(false)
    expect(PROFILE.addressRegex.mainnet.test('EC' + 'a'.repeat(100))).toBe(false)
  })

  it('mainnet PQ class covers the reachable 26k–26n range', () => {
    expect(PROFILE.addressRegex.mainnet.test(`26k${tail}`)).toBe(true)
    expect(PROFILE.addressRegex.mainnet.test(`26m${tail}`)).toBe(true)
    expect(PROFILE.addressRegex.mainnet.test(`26n${tail}`)).toBe(true)
    expect(PROFILE.addressRegex.mainnet.test(`26j${tail}`)).toBe(false) // unreachable
  })

  it("testnet PQ class covers the reachable 2A4–2A6 range, not the node's old 2A[678]", () => {
    expect(PROFILE.addressRegex.testnet.test(`2A4${tail}`)).toBe(true)
    expect(PROFILE.addressRegex.testnet.test(`2A5${tail}`)).toBe(true)
    expect(PROFILE.addressRegex.testnet.test(`2A6${tail}`)).toBe(true)
    expect(PROFILE.addressRegex.testnet.test(`2A7${tail}`)).toBe(false) // unreachable
    expect(PROFILE.addressRegex.testnet.test(`2A8${tail}`)).toBe(false) // unreachable
  })
})
