import { describe, expect, it } from 'vitest';
import {
  addressFromPubkey,
  addressFromScripthash,
  decodeAddress,
  scripthashFromPubkey,
  validateAddress,
} from './address';
import { ADDRESS_REGEX } from './constants';
import { fromHex, toHex } from './encoding/hex';
import { hash256 } from './hashes';
import { scriptP2PK } from './script';

// Real-world mainnet test vectors from the live mempool dump. Each row is
// taken from one tx in
// a live node's `/api/mempool/recent` and re-encoded with this base's
// magic — encoding-level goldens. These are the most
// authoritative test vectors we have — if our implementation produces
// the same address as the node from the same pubkey, we're byte-compat.

interface PubkeyVector {
  pubkey: string;
  scripthash: string;
  address: string;
}

const MAINNET_PUBKEY_VECTORS: PubkeyVector[] = [
  {
    pubkey:
      '039b66566d3acb6bd203a0a61f4e0105b84f12e107aaf27f30466807121197d10c',
    scripthash: 'a63aa6b72ec7668ee5529a2d4706b7ac8239a4a2',
    address: 'bqcBXGDnSrGiiPVvqNXtyHboKj2oWKrLZWv',
  },
  {
    pubkey:
      '02b17362c10f06ff75a7039798de7301991fc371aeccf1aba3c8849a2f3f06322c',
    scripthash: '38a3a70af85baab9455c148fa2ce83657d9a484c',
    address: 'bqSC4ijgCXhsjb9eikvex3pSUhcbWUmsSfU',
  },
];

// scripthash ↔ address pairs (no pubkey known — used only for the
// scripthash→address direction).
const MAINNET_SCRIPTHASH_PAIRS: Array<{ scripthash: string; address: string }> = [
  { scripthash: 'de4bde2de43a35b7538e9992b94f2c29bec01e8b', address: 'bqhHyjCRyAG5p1Ai3h9WgCyPYcaQ4zahzDo' },
  { scripthash: 'ad5ef5738c9b3e8de242e75d3f99c5b92a49a25a', address: 'bqcqHVFtzYDqkWQomA1GtvHdfabDjuaWVWJ' },
  { scripthash: 'b9aeee3da2449c03ab85eaa772754459292b1e40', address: 'bqdxPQ6kjoUwGytf1V1sw6VrquwPb3SA1zP' },
  { scripthash: 'cd5e217bbc2e368a398ba6130aba5187ea689ca2', address: 'bqfkU7sAhij1biFtiuG1r64wwXg8CFWNuD2' },
  { scripthash: '827ea2d412a1c9e1f859d9a8daadc4921a0237c4', address: 'bqYvaNyyYbCc7Se341khkfryLedaF9fCGrm' },
  { scripthash: '3795a4207eed2182225da6866b45edfddb095e5c', address: 'bqS6VG1u8J8UfKC5hoPmLtJwXm3SYrLNhGk' },
];

describe('scripthashFromPubkey — live mempool vectors', () => {
  it.each(MAINNET_PUBKEY_VECTORS)(
    'matches scripthash for $address',
    ({ pubkey, scripthash }) => {
      const computed = scripthashFromPubkey(fromHex(pubkey), 'ecdsa');
      expect(toHex(computed)).toBe(scripthash);
    },
  );
});

describe('addressFromPubkey — live mempool vectors', () => {
  it.each(MAINNET_PUBKEY_VECTORS)(
    'derives $address from its pubkey',
    ({ pubkey, address }) => {
      expect(addressFromPubkey(fromHex(pubkey), 'ecdsa', 'mainnet')).toBe(address);
    },
  );
});

describe('addressFromScripthash — round-trip with live data', () => {
  it.each(MAINNET_SCRIPTHASH_PAIRS)(
    'encodes $address',
    ({ scripthash, address }) => {
      expect(addressFromScripthash(fromHex(scripthash), 'mainnet')).toBe(address);
    },
  );

  it('rejects scripthash with unexpected length', () => {
    expect(() => addressFromScripthash(new Uint8Array(19), 'mainnet')).toThrow(RangeError);
    expect(() => addressFromScripthash(new Uint8Array(21), 'mainnet')).toThrow(RangeError);
    expect(() => addressFromScripthash(new Uint8Array(31), 'mainnet')).toThrow(RangeError);
  });

  it('accepts both 20-byte and 32-byte scripthashes', () => {
    expect(() => addressFromScripthash(new Uint8Array(20), 'mainnet')).not.toThrow();
    expect(() => addressFromScripthash(new Uint8Array(32), 'mainnet')).not.toThrow();
  });
});

describe('validateAddress', () => {
  it.each(MAINNET_SCRIPTHASH_PAIRS)('accepts live mainnet address $address', ({ address }) => {
    expect(validateAddress(address, 'mainnet')).toBe(true);
  });

  it('rejects mainnet address on testnet network', () => {
    expect(validateAddress('bqcBXGDnSrGiiPVvqNXtyHboKj2oWKrLZWv', 'testnet')).toBe(false);
  });

  it('rejects addresses with bad checksum', () => {
    // Flip one character in a real address — checksum will fail.
    const real = 'bqcBXGDnSrGiiPVvqNXtyHboKj2oWKrLZWv';
    const tampered = real.slice(0, -1) + (real.at(-1) === '1' ? '2' : '1');
    expect(validateAddress(tampered, 'mainnet')).toBe(false);
  });

  it('rejects empty / gibberish', () => {
    expect(validateAddress('', 'mainnet')).toBe(false);
    expect(validateAddress('not an address at all', 'mainnet')).toBe(false);
  });
});

// ─── Post-quantum (Falcon-512) addresses ──────────────────────────────
//
// Synthetic deterministic 897-byte pubkey (0x09 version byte + pattern).
// Expected values were generated by this implementation and FROZEN — they
// pin the PQ encoding: scripthash = hash256(P2PK script), 32-byte form.
// The full mnemonic→address chain is pinned in falconHd.test.ts.

function syntheticFalconPubkey(): Uint8Array {
  const pk = new Uint8Array(897);
  pk[0] = 0x09;
  for (let i = 1; i < pk.length; i++) pk[i] = i % 256;
  return pk;
}

const PQ_SCRIPTHASH =
  'a996d29978cadc7100f8ee23fc408bbcbadc4500564ba02989e55b772494f280';
const PQ_MAINNET_ADDRESS =
  '3uJTRh2ppxgJs4hwEYaehjM329q1iENgJ7krJgPJV6x7YA3FuuRx';
const PQ_TESTNET_ADDRESS =
  '3ua3ntuyNG6Gmhw8eXH4SMatYGUZJKuz17AfQrZRaV9w992Q7giSa';

describe('post-quantum (falcon512) address encoding', () => {
  it('scripthash = hash256(scriptP2PK(pubkey)), 32 bytes', () => {
    const pk = syntheticFalconPubkey();
    const sh = scripthashFromPubkey(pk, 'falcon512');
    expect(sh.length).toBe(32);
    expect(toHex(sh)).toBe(PQ_SCRIPTHASH);
    // Cross-check the construction explicitly: hash256 over the P2PK script.
    expect(toHex(sh)).toBe(toHex(hash256(scriptP2PK(pk))));
  });

  it('encodes the frozen mainnet/testnet PQ addresses', () => {
    const pk = syntheticFalconPubkey();
    expect(addressFromPubkey(pk, 'falcon512', 'mainnet')).toBe(
      PQ_MAINNET_ADDRESS,
    );
    expect(addressFromPubkey(pk, 'falcon512', 'testnet')).toBe(
      PQ_TESTNET_ADDRESS,
    );
  });

  it('PQ addresses match the network regex and validate', () => {
    expect(ADDRESS_REGEX.mainnet.test(PQ_MAINNET_ADDRESS)).toBe(true);
    expect(ADDRESS_REGEX.testnet.test(PQ_TESTNET_ADDRESS)).toBe(true);
    expect(validateAddress(PQ_MAINNET_ADDRESS, 'mainnet')).toBe(true);
    expect(validateAddress(PQ_TESTNET_ADDRESS, 'testnet')).toBe(true);
    expect(validateAddress(PQ_MAINNET_ADDRESS, 'testnet')).toBe(false);
  });

  it('decodes round-trip as type pq', () => {
    const dec = decodeAddress(PQ_MAINNET_ADDRESS);
    expect(dec.type).toBe('pq');
    expect(dec.network).toBe('mainnet');
    expect(toHex(dec.scripthash)).toBe(PQ_SCRIPTHASH);
    expect(addressFromScripthash(dec.scripthash, 'mainnet')).toBe(
      PQ_MAINNET_ADDRESS,
    );
  });

  it('the HD-derived golden address (falconHd cell 0,0,0) is a valid pq address', () => {
    const addr = '3uJGP7n3KwZkHa2YzML1YvWUSdBhnNM5fC1WTfeyd62q2XLny8xd';
    expect(validateAddress(addr, 'mainnet')).toBe(true);
    expect(decodeAddress(addr).type).toBe('pq');
  });
});

describe('decodeAddress', () => {
  it.each(MAINNET_SCRIPTHASH_PAIRS)('decodes $address', ({ scripthash, address }) => {
    const dec = decodeAddress(address);
    expect(dec.network).toBe('mainnet');
    expect(dec.type).toBe('classical');
    expect(toHex(dec.scripthash)).toBe(scripthash);
  });

  it('round-trips via addressFromScripthash', () => {
    const original = 'bqcBXGDnSrGiiPVvqNXtyHboKj2oWKrLZWv';
    const dec = decodeAddress(original);
    expect(addressFromScripthash(dec.scripthash, dec.network)).toBe(original);
  });

  it('throws on garbage', () => {
    expect(() => decodeAddress('garbage')).toThrow();
  });

  it('throws on tampered checksum', () => {
    const real = 'bqcBXGDnSrGiiPVvqNXtyHboKj2oWKrLZWv';
    const tampered = real.slice(0, -1) + (real.at(-1) === '1' ? '2' : '1');
    expect(() => decodeAddress(tampered)).toThrow();
  });
});
